### ISSUE TITLE
doesn't build with latest brunsli

### ISSUE THREAD

**Issue by mmilkovski** [ptiszai/brunsli_win#1]
Hello,

thanks for your contribution! 

I did follow your instructions and no success... could you please try/check and make it work with latest brunsli version ? 
I receive silly errors like 'JPEGOutput' is not member of 'brunsli' 

Thank you

**Comment by ptiszai** [comment]
Hello,

The Google changed the brunsli project,  i corrected my project.

Kind Regards,
Tiszai

**Comment by mmilkovski** [comment]
Yes, Google updated the project and now your wrapper works as well.

Thank you very much Tiszai.
